### ISSUE TITLE
Hash values

### ISSUE THREAD

**Issue by tom-seddon** [chainpoint/whitepaper#1]
The hashes for ecah parent are made starting by concatenating ASCII strings containing its children's hashes expressed in hex, rather than the hash results themselves. I found this a bit surprising - is this intentional? If it is then the description should perhaps be explicit about it.

Thanks,

--Tom

**Comment by jasonbukowski** [comment]
The Chainpoint 2.0 specification concatenates the hashes as binary, no longer as their hex string representations.
