### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by lontivero** [chainpoint/whitepaper#3]
Hi @jasonbukowski, i've created a python library for Chainpoint. Here you can see it:
- [Python Chainpoint package](https://pypi.python.org/pypi/Chainpoint/0.0.1)
- [GitHub PyChainpoint repository](https://github.com/lontivero/PyChainpoint)

I hope this is useful for the community.
Thanks

**Comment by jasonbukowski** [comment]
That's great, thank you for your contribution!
