### ISSUE TITLE
How chainpoint works

### ISSUE THREAD

**Issue by selvam347** [chainpoint/whitepaper#5]
I am new to blockchain technology and know some of the basics of blockchain technology. I can understand how [proof of existence](https://proofofexistence.com/about) works. But feeling little bit difficult in understanding chainpoint. Proof of existence stores **target hash** in **OP_RETURN**. But chaincode stores merkle root. I can understand how merkle root formed from [here](https://brilliant.org/wiki/merkle-tree/). But i do not know chaincode forms merkle tree. For example consider i have a target hash as bdf8c9bdf076d6aff0292a1c9448691d2ae283f2ce41b045355e2c8cb8e85ef2 and got the following receipt.
`{
 "@context": "https://w3id.org/chainpoint/v2",
 "type": "ChainpointSHA256v2",
 "targetHash": "bdf8c9bdf076d6aff0292a1c9448691d2ae283f2ce41b045355e2c8cb8e85ef2",
 "merkleRoot": "51296468ea48ddbcc546abb85b935c73058fd8acdb0b953da6aa1ae966581a7a",
 "proof": [
   {
     "left": "bdf8c9bdf076d6aff0292a1c9448691d2ae283f2ce41b045355e2c8cb8e85ef2"
   },
   {
     "left": "cb0dbbedb5ec5363e39be9fc43f56f321e1572cfcf304d26fc67cb6ea2e49faf"
   },
   {
     "right": "cb0dbbedb5ec5363e39be9fc43f56f321e1572cfcf304d26fc67cb6ea2e49faf"
   }
 ],
 "anchors": [
   {
     "type": "BTCOpReturn",
     "sourceId": "f3be82fe1b5d8f18e009cb9a491781289d2e01678311fe2b2e4e84381aafadee"
   }
 ]
}`
Here i am having the following questions.
1. How did you get proof array.
2. who is giving receipt id?
2. you are storing merkle root alone in blockchain. Then where are you storing the above receipt?

**Comment by jasonbukowski** [comment]
#### How do you get the proof array?
The proof array represents the path of calculations to go from a leaf of the merkle tree, in this case your target hash, to the tree's root. As you progress from the leaf to the root, you concatenate and hash with the working node's sibling value until you arrive at the root. This process is (loosely) depicted in the whitepaper on page 2, image 3 and in the image below.

![Image of merkle proof path](https://i.stack.imgur.com/2Ep7y.png)

In the above example, the green node represents your target hash. The blue nodes are the sibling nodes that you would concatenate and hash to arrive at the next level's value. The left/right operations in the proof array represent these blue nodes and describe the necessary concatenate and hash operations to get you from the target hash to the merkle root.

#### Who is giving the receipt Id?
Currently, the receipt Id acts only as a unique identifier for a receipt. It is created and assigned to proofs by whatever system is generating the Chainpoint proofs. The receipt Ids should be some form of globally unique identifier to avoid collision. An upcoming release of Chainpoint will enforce time encoded UUIDs for the receipt Id.

#### Where are you storing the receipt?
Long term storage of the receipt is handled by whatever system is generating the Chainpoint receipts, and can vary from implementation to implementation.
